// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhnljpccbukwshvkdooj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVobmxqcGNjYnVrd3Nodmtkb29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjgwNzgsImV4cCI6MjA2NDE0NDA3OH0.uZe7b_u7ZkrdHI6WzTQn_yiiHnWRVQnJaF_OFqDJevg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);